### ISSUE TITLE
Compiler Test Suite

### ISSUE THREAD

**Issue by adishavit** [arnemertz/online-compilers#4]
@arnemertz : Can you add your compiler version testing code that you used to evaluate each platform to the repo?

I think you posted a gist of it somewhere, but here seems like natural place to keep it.

**Comment by adishavit** [comment]
Is this it: https://gist.github.com/arnemertz/5f1e3c235b9ea9e3b803ecdb2ae80805

**Comment by arnemertz** [comment]
yes, that's the one. Will add it
