### ISSUE TITLE
Consider adding Codiad

### ISSUE THREAD

**Issue by Samuel-Berger** [arnemertz/online-compilers#6]
I stumbled upon [Codiad](http://codiad.com/) when researching possible web based C++ IDEs to use. I was not able to launch a C++ project and compile it using the [demo available](http://demo.codiad.com/), but one thing it has is the possibility to run it self hosted. So it may be suitable for schools and such who wants to be able to track the students progress, unlike other online IDEs that seldom offers that possibility.

**Comment by arnemertz** [comment]
Thanks, I'll have a look. Pull requests are also always welcome ;)

**Comment by arnemertz** [comment]
Having syntax highlighting in C++ files seems to work, but could not find options to compile and execute.
See my question on their GitHub repo: https://github.com/Codiad/Codiad/issues/1026

**Comment by arnemertz** [comment]
Apparently does not work out-of-the-box for C++, thus for now not in the scope of the page.
